# Generated by Django 5.0.6 on 2024-12-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peer", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="peer_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
